name: build and test
on: [pull_request]

jobs:
  build:
    name: "Build and Test on os: ${{ matrix.os }}. dotnet SDK version: ${{ matrix.dotnet }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        dotnet: ['3.0.100', '3.1.200']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      # we alsot wanted to cache ~/.cargo , but actions/cache seems to not work well with actions-rs/toolchain
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: rust-lightning/target
          key: ${{ matrix.os }}-cargo-build-target-${{ hashFiles('rust-lightning/Cargo.lock') }}-${{ hashFiles('rust-lightning/**/src/**') }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build with dotnet
        run: |
          dotnet build --configuration Debug src/NRustLightning

      - name: Run test in ${{ matrix.os }}
        if: startsWith(matrix.dotnet, '3.1')
        run: dotnet test tests/NRustLightning.Tests