name: build and deploy
on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, windows-latest, macos-latest]
        dotnet: ['3.0.100', '3.1.200']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build with dotnet
        run: dotnet build --configuration Release NRustLightning
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, windows-latest, macos-latest]
        dotnet: ['3.1.200']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Run test in ${{ matrix.os }}
        run: ./test.sh
  pack:
    runs-on: ubuntu-18.04
    needs: [build, test]
    steps:
    - name: dotnet pack
      run: |
        dotnet pack -p:Configuration=Release
    - name: push to nuget
      run: |
        dotnet nuget push ./bin/Release/NRustLightning.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json