name: build and deploy
on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, windows-latest, macos-latest]
        dotnet: ['2.2.103', '3.1.200']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Run test
        run: ./test.sh
  pack:
    runs-on: ubuntu-18.04
    steps:
    - name: dotnet pack
      run: |
        dotnet pack -p:Configuration=Release
    - name: push to nuget
      run: |
        dotnet nuget push ./bin/Release/NRustLightning.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json