name: build and deploy
on: [pull_request]

jobs:
  build:
    name: "Build on os: ${{ matrix.os }}. dotnet SDK version: ${{ matrix.dotnet }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, windows-latest, macos-latest]
        dotnet: ['3.0.100', '3.1.200']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build with dotnet
        run: dotnet build --configuration Release src/NRustLightning
  test:
    name: "Test on os: ${{ matrix.os }}. dotnet SDK version: ${{ matrix.dotnet }}"
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, windows-latest, macos-latest]
        dotnet: ['3.1.200']
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup ${{ matrix.dotnet }} .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Run test in ${{ matrix.os }}
        run: dotnet test tests/NRustLightning.Tests
  pack:
    runs-on: ubuntu-18.04
    needs: [build, test]
    steps:
    - name: pack and push to nuget
      run: |
        if [ ${{ secrets.NUGET_API_KEY }} ] && [ $GITHUB_REF == "refs/heads/master" ]; then
          dotnet pack -p:Configuration=Release src/NRustLightning
          dotnet nuget push ./src/NRustLightning/bin/Release/NRustLightning.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        fi
