name: publish(master)
on:
  push:
    branches:
      - master
      - ci

jobs:
  pack_and_push:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup 3.1.200 .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Build with dotnet
        run: dotnet build --configuration Release src/NRustLightning
      - name: pack and push to nuget
        run: |
          if [ ${{ secrets.NUGET_API_KEY }} ]; then
            dotnet pack -p:Configuration=Release src/NRustLightning --version-suffix date`date +%Y%m%d-%H%M`.git-`echo $GITHUB_SHA | cut -c 1-7`
            dotnet nuget push ./src/NRustLightning/bin/Release/NRustLightning.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
          fi
